Creating footer
Christianib003/Portfolio-Moblie-Skeleton-Version pull request #5
Opened 2022-01-21 15:04 UTC by Christianib003

I this milestone, I added:
1. Contact form
2. Submit button

2022-01-21 15:58 UTC, Meltrust requested changes
Hi @Christianib003, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Please from now on, submit your next reviews to the same pull request instead of creating a new one.  Cheers!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 15:58 UTC, Meltrust commented on index.html
> +        <button type="submit" class="submit">Get in touch</button>
- [ ] This button is not working.  The reason is that it is outside your `<form>` tag.  

Please kindly just move the `<button type="submit" class="submit">Get in touch</button>` line to be inside your form tag. 

![image](https://user-images.githubusercontent.com/57421823/150558450-b0a4eec9-ff60-46b5-a79b-e556d59462d3.png)

That way, your button will start working 💪

2022-01-22 06:34 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @Christianib003 ,  

Great work on making the changes requested by a previous reviewer 👏🏻 
Your project is complete! Congratulations!  🎉💯🌟 

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 06:34 UTC, ShoiraTa commented on index.html
> +    <section class="last">
- [ ] [OPTIONAL] This section has a fixed height of `800px`, and therefore the purple background is being over before the form is over: 

![image](https://user-images.githubusercontent.com/77038610/150627863-2e7355e8-77aa-434b-be21-fea82d31110a.png)

I strongly suggest to delete the ` height: 800px;` property to fix this issue.

2022-01-22 14:37 UTC, merged

2022-03-21 12:49 UTC, VICTOR-CHUKWU reviewed
Hi @Christianib003 , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._