Desktop version
Christianib003/Portfolio-Moblie-Skeleton-Version pull request #6
Opened 2022-01-22 15:29 UTC by Christianib003

In this milestone, OI added
1. Media queries for the desktop version of a minimum width of 992px.
2. Changed background images for the first section and a contact form.
3.  Navigation bar for the desktop version.

2022-01-22 17:02 UTC, Rustamxon7 requested changes
Hi @Christianib003   , 

Good job so far!

### HIGHLIGHTS!

- No linters errors.💯
- Descriptive Readme.md. 💯


There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 17:02 UTC, rustam-tolipov commented on index.html
> +                    <button type="button" class="seeProject">See Project</button>
- [ ] **GOOD JOB SO FAR** 👏. Please add a hover effect to buttons to make your buttons better look. You can see img below between default hover effect colors.

## Image of button states
![image](https://user-images.githubusercontent.com/69011963/150648008-3bfd6742-915b-4286-b228-dafc129374b4.png)

2022-01-22 17:02 UTC, rustam-tolipov commented on index.html
>              </ul>
- [ ] Last issue in the desktop version is that `let's connect` button and social icons are centered. Please move them to the left side and with that, your desktop version will be completed 💯👍

#### You can see your website below
![image](https://user-images.githubusercontent.com/69011963/150648103-c0b0e5a7-153b-4dc6-a5ce-164bca33b48a.png)

#### The figma design
![image](https://user-images.githubusercontent.com/69011963/150648133-72f8e46a-c3fd-4ebb-8d4f-a935810c8965.png)

2022-01-22 17:02 UTC, Rustamxon7 commented on index.html
> +            <textarea name="message" class="area message" maxlength="500" placeholder="Write your message here" required></textarea>
- [ ] There is just one issue in your mobile version that I am sure you can fix it 💻. Please kindly increase the height of textarea which helps users send you more messages when they want to contact you 🤗🍀

#### Your design
![image](https://user-images.githubusercontent.com/69011963/150648258-9b36b847-5739-42a3-8a49-efc2fbe0e088.png)

#### Figma design
![image](https://user-images.githubusercontent.com/69011963/150648288-a892fc80-a084-4be2-949c-00e34951b16a.png)

2022-01-22 20:30 UTC, Hamzaoutdoors requested changes
Hi @Christianib003, 

Great work on making the changes requested by a previous reviewer 👏 👏🏼 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 20:30 UTC, Hamzaoutdoors commented on index.html
> +    <section class="About Myself">
- [x] Great job working on changes requested by the previous reviewer, But unfortunately, you need to stick to the design as much as possible for better UI (user interface) and this is a good professional practice that every frontend software developer should maintain. Please, make sure to layout this section `About section`  so they can look closely similar to the [original design](https://www.figma.com/file/t3EJUCAEViw3QasuJLPLVT/Microverse-Student-Potfolio-Templates-Main?node-id=1%3A1471) 😸 .

You can use `flex-direction: column;` in the CSS what do you think

## **Your project**
![real](https://user-images.githubusercontent.com/80895497/150654358-5f39dad3-9e79-438a-aa12-bd7d626dc198.PNG)

## **Design**
![design](https://user-images.githubusercontent.com/80895497/150654359-cd0f1ebe-0d77-41e2-82a6-64af01a54cdf.PNG)

2022-01-22 21:21 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢 

### Hi @Christianib003 👋🏻, 

You have done a tremendous job making the changes requested 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 21:26 UTC, merged

2022-03-21 13:20 UTC, mikethreels reviewed
Hi Christian, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that was already approved, I saw your message that you are repeating the module however in that case you need to create a new repo and start the project from scratch, you can copy the code you already used from your old project but you can't send merged PR for review again. alternatively, you can revert the project to the first commit and start all over again (although I don't recommend this option).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-21 16:18 UTC, Amrhub commented
Hi @Christianib003,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.


## Required Changes ♻️
_Check the comments under the review._
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

- [ ] [REQUIRED] I know you are repeating the week unfortunately the new Microverse system requires you to just make a new PR. you can't use a previous one. that's all you are missing for approval. It would be appreciated if you let your next reviewer about this situation probably linking this PR

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 16:30 UTC, iKrystyan commented
Does it mean I will have to start a new project? @Amrhub

2022-03-21 16:42 UTC, Amrhub commented
You can copy and paste but has to be a fresh new